### ISSUE TITLE
Make a wrap content option

### ISSUE THREAD

**Issue by VenomRaiden** [marcusolsson/obsidian-projects#648]
### What would you like to be added?

A open in coloums to wrap the content of a coloum

### Why is this needed?

To be able to see a long filename without having to open it

**Comment by Acylation** [comment]
I got your point. This needs some design on UI and view settings.

**Comment by Acylation** [comment]
Related to #635 where raised the request to wrap the column header. The two issues can be solved together.

**Comment by puffybc** [comment]
Maybe I'm doing something wrong, but the content field is a tiny box and I have multiple paragraphs to put into it. 
I'm used to Trello where there's a huge field you can edit. That's the first thing you see. And beneath it is a Checklist. 
However in Projects, I am unable to read my text because the field is too small and it does not wrap.

**Comment by stoweboyd** [comment]
Same issue with text fields. 

I have been using a hack where I insert `<br>` to break long text fields, which 'works' but is laborious to fool with. Also, if I attempt to add a break that way while editing in table view (not in the YAML of the note) I have had the entire text field wiped out by a double break: `<br><br>`. Extremely annoying.

**Comment by mthanasi** [comment]
I had the same issue and fixed it with a custom Obsidian [CSS snippet](https://help.obsidian.md/snippets). It forces table cells (but not headers) to wrap long content and tags nicely in Table view. Here’s what I used:

```css
/* Only wrap gridcell content (not headers) */
[role="gridcell"] {
  white-space: normal !important;
  overflow-wrap: break-word !important;
  word-break: break-word !important;
  overflow: hidden !important;
  text-align: left !important;
  display: block !important;
}

[role="columnheader"],
[role="rowheader"] {
  white-space: nowrap !important;
  overflow: hidden !important;
  text-overflow: ellipsis !important;
}

/* Allow tag group to wrap to next line */
[role="gridcell"] > div {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: flex-start; /* Left-align tags */
  gap: 4px;
  padding: 4px;

  white-space: normal !important;
  word-wrap: break-word !important;
  overflow-wrap: break-word !important;
  text-overflow: initial !important;
}

/* Prevent individual tags from wrapping mid-word */
[role="gridcell"] .tag,
[role="gridcell"] .rich-text-tag {
  white-space: nowrap !important;
  flex-shrink: 0;
}
```

Hope that helps!
