### ISSUE TITLE
A possibility to fold/unfold options bar.

### ISSUE THREAD

**Issue by DeusEx01** [marcusolsson/obsidian-projects#711]
### What would you like to be added?

I've noticed the issue while using mobile version. Options bar takes too much space. It'd be great to add some button to fold(hide)/unfold options. I'll attach a screenshot with issue. It takes about 40% of space, it could be an additional row for example. 
Meanwhile, I'll try to add it manually via JS...

### Why is this needed?

It will give us more useful space.

Issue: ![экран1](https://github.com/marcusolsson/obsidian-projects/assets/149239010/0eaabb77-c870-45b4-aba2-4fda14524416)
Solution(my example): ![экран2](https://github.com/marcusolsson/obsidian-projects/assets/149239010/c6111697-6dfb-4b20-87f6-6e97432f880d)

**Comment by Acylation** [comment]
A possible improvement on this is to display view list vertically, raised by #601. The meta topin of mobile support is #161 FYI

**Comment by danvolchek** [comment]
I'd love this too! On my device, the project selector/view selector/color + filter + sort/view settings options take up a really large portion of the screen. A way to show/hide all of that would be really nice.

**Comment by Sagi-Rastar** [comment]
Hi All
I encountered a similar problem with this issue when using this plugin, and after searching around for solutions I decided to implement it myself by introducing a short css snippet.

```css
/* Folded - Base on hover */
.container.svelte-3iuity.isMobile {
  max-height: 1px; 
  overflow: hidden;
  transition: max-height 0.3s ease;
  position: relative;
  border-bottom: 0.5em solid #f0f0f000 !important;
  padding-bottom: 1em !important;
}

.svelte-h4e1e6 {
  padding-top: 1em !important;
}

.container.svelte-3iuity.isMobile:hover,
.container.svelte-3iuity.isMobile:focus-within {
  max-height: 300px;
}

/* Simple "icon" */
.container.svelte-3iuity.isMobile::after {
  content: "=";
  position: absolute;
  right: 10px;
  top: 1px;
  bottom: 1px;
  font-size: 18px;
  font-weight: bold;
  transition: transform 0.3s;
}
```

This should just be a workaround, and friends who are hoping to temporarily alleviate the problem can give this less-than-elegant solution a try.

_Test effect:_

> Theme: Minimal

![Image](https://github.com/user-attachments/assets/64dc3d82-c71d-4fe8-ae90-6f5695334d27)

![Image](https://github.com/user-attachments/assets/126867f5-df85-4301-b98b-27e0243b076e)

> PC

![Image](https://github.com/user-attachments/assets/17adad4b-bf69-450a-b10f-396a8c1c9438)

![Image](https://github.com/user-attachments/assets/040874d9-ecba-4786-8518-00ea31aa2812)

> IOS （trigger the hover property by tapping）
