### ISSUE TITLE
Support to YAML objects

### ISSUE THREAD

**Issue by hyungtaecf** [marcusolsson/obsidian-projects#810]
### What would you like to be added?

Support to target nested fields.
```yml
cartParams:
  - title: Leg type 
    options:
      - Round
      - Square
  - title: Leg width / diameter 
    options:
      - 1.00 inches
      - 1.25 inches
      - 1.50 inches
      - 1.75 inches
      - 2.00 inches
```

Allowing properties like `cartParams.title` to show in the result.

### Why is this needed?

This enhancement would enable users to organize their frontmatter in a more structured manner, especially in cases where a vault serves multiple purposes and involves a significant amount of frontmatter. Utilizing object-like structures for properties, such as the example provided, offers a cleaner approach to managing data, prevents cluttering of property lists, and facilitates the separation of different types of notes that share the same property name. Additionally, this enhancement aligns well with plugins like Dataview, allowing for more versatile and powerful usage scenarios.
